---
volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro
  process_exporter:
    image: ncabatoff/process-exporter
    container_name: process_exporter
    ports:
      - 9256:9256
    restart: unless-stopped
    volumes:
      - /proc:/host/proc
      - ./config:/config
    privileged: true
    command: --procfs /host/proc -config.path /config/process-exporter.yaml
